### ISSUE TITLE
Investigate and fix "Undefined index order" error from RC Subsites

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1118]
## Why
There are lots of error messages with "Undefined index  error" in the logs, every day.  We should fix the problem producing the logs or stop logging it as an error

## What
- [ ] Error found in the logs are investigated and the issue is fixed or the message is logged using another log level

## Notes
Error appears for RC Subsites, production.
```
Sep 02 19:58:54 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 19:58:54 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 19:58:54 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 19:58:54 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 20:01:00 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:01:00 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 20:01:00 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:01:00 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 20:16:31 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:16:31 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 20:16:31 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:16:31 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 20:20:52 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:20:52 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 20:20:52 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:20:52 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 20:21:07 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:21:07 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 20:21:07 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:21:07 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 20:37:10 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:37:10 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 20:37:10 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:37:10 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 20:47:54 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:47:54 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 20:47:54 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:47:54 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 20:51:19 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:51:19 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 20:51:19 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:51:19 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 20:56:02 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:56:02 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 20:56:02 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:56:02 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 20:57:28 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:57:28 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 20:57:28 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 20:57:28 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 21:09:07 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 21:09:07 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 21:09:07 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 21:09:07 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 21:21:14 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 21:21:14 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 21:21:14 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 21:21:14 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 21:25:47 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 21:25:47 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 21:25:47 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 21:25:47 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 21:41:20 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 21:41:20 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 21:41:20 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 21:41:20 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 21:56:16 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 21:56:16 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 21:56:16 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 21:56:16 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 22:00:17 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 22:00:17 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 22:00:17 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 22:00:17 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 22:05:47 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 22:05:47 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 22:05:47 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 22:05:47 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 22:24:26 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 22:24:26 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 22:24:26 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 22:24:26 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 22:29:04 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 22:29:04 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 22:29:04 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 22:29:04 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 02 22:29:51 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 22:29:51 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 02 22:29:51 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 02 22:29:51 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 03 07:54:50 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs:  Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 03 07:54:50 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs:  #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 03 07:54:50 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs:  Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 03 07:54:50 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs:  #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 03 07:57:12 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs:  Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 03 07:57:12 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs:  #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 03 07:57:12 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs:  Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 03 07:57:12 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs:  #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 03 08:25:16 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs:  Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 03 08:25:16 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs:  #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 03 08:25:16 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs:  Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 03 08:25:16 7aaa26c24de5 ecs-rc-subsite-master-var-www-rc-storage-logs:  #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Sep 03 08:43:47 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs:  Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 03 08:43:47 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs:  #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Sep 03 08:43:47 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs:  Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/search_list.blade.php)' in /var/www/rc/storage/framework/views/6f2b144fb752b76c82eb363664ff9e6d:203
Sep 03 08:43:47 aa93022ba422 ecs-rc-subsite-master-var-www-rc-storage-logs:  #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
```

**Comment by adinuca** [comment]
Hi @anjesh, could you please take a look at this issue. The error is present only in the Production logs, but this might be because Staging is not used as much.

Thank you!

**Comment by charlesyoung** [comment]
@adinuca could you investigate more or do you need YI's help?

**Comment by adinuca** [comment]
Hi @charlesyoung ,

We can investigate this but it would probably take us a bit longer to fix it than it would take YI.

**Comment by man-git007** [comment]
@adinuca This issue have been resolved.

cc @anjesh

**Comment by adinuca** [comment]
You can close this is it has been deployed to production.

**Comment by charlesyoung** [comment]
@adinuca has this been tested on Prod?
