### ISSUE TITLE
Fix "Undefined index: tag_line_olc" error

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1167]
## Why
Production logs are flooded with the error "Undefined index: tag_line_olc" which might mean users see an error.

## What
- [ ] Error is investigated and problem is fixed or message log level is changed if it is not actually an error.

## Notes
```
Dec 27 06:13:28 8c6803d40fab ecs-rc-subsite-master-var-www-country-drc-storage-logs:  #0 /var/www/country-drc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Dec 27 06:13:29 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  Stack trace:
Dec 27 06:13:29 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  #0 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(408): Illuminate\View\View->__call('send', Array)
Dec 27 06:13:29 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  #1 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(408): Illuminate\View\View->send()
Dec 27 06:13:29 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  #2 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(348): Laravel\Lumen\Application->handleUncaughtException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
Dec 27 06:13:29 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  #3 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}()
Dec 27 06:13:29 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  #4 {main}
Dec 27 06:13:29 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:    thrown in /var/www/country-drc/vendor/illuminate/view/View.php on line 392" while reading response header from upstream, client: ::ffff:10.0.1.156, server: drc.openlandcontracts.org, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "52.86.151.147"
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-var-www-country-drc-storage-logs:  Next exception 'ErrorException' with message 'Undefined index: tag_line_olc (View: /var/www/country-drc/resources/views/layout/partials/head.blade.php)' in /var/www/country-drc/app/Http/Services/SiteService.php:141
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-var-www-country-drc-storage-logs:  #0 /var/www/country-drc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-var-www-country-drc-storage-logs:  Next exception 'ErrorException' with message 'Undefined index: tag_line_olc (View: /var/www/country-drc/resources/views/layout/partials/head.blade.php) (View: /var/www/country-drc/resources/views/layout/partials/head.blade.php)' in /var/www/country-drc/app/Http/Services/SiteService.php:141
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-var-www-country-drc-storage-logs:  #0 /var/www/country-drc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 2)
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-var-www-country-drc-storage-logs:  Next exception 'ErrorException' with message 'Undefined index: tag_line_olc (View: /var/www/country-drc/resources/views/layout/partials/head.blade.php) (View: /var/www/country-drc/resources/views/layout/partials/head.blade.php) (View: /var/www/country-drc/resources/views/layout/partials/head.blade.php)' in /var/www/country-drc/app/Http/Services/SiteService.php:141
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-var-www-country-drc-storage-logs:  #0 /var/www/country-drc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-var-www-country-drc-storage-logs:  #2 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(341): Laravel\Lumen\Application->handleUncaughtException(Object(ErrorException))
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-var-www-country-drc-storage-logs:  #3 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(ErrorException))
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  Stack trace:
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  #0 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(408): Illuminate\View\View->__call('send', Array)
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  #1 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(408): Illuminate\View\View->send()
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  #2 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(341): Laravel\Lumen\Application->handleUncaughtException(Object(ErrorException))
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  #3 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(ErrorException))
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  #4 {main}
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:    thrown in /var/www/country-drc/vendor/illuminate/view/View.php on line 392
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  Stack trace:
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  #0 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(408): Illuminate\View\View->__call('send', Array)
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  #1 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(408): Illuminate\View\View->send()
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  #2 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(348): Laravel\Lumen\Application->handleUncaughtException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  #3 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}()
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:  #4 {main}
Dec 27 06:13:47 8c6803d40fab ecs-rc-subsite-master-nginx-error.log:    thrown in /var/www/country-drc/vendor/illuminate/view/View.php on line 392" while reading response header from upstream, client: ::ffff:10.0.1.156, server: drc.openlandcontracts.org, request: "GET /robots.txt HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "52.86.151.147"
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-var-www-country-drc-storage-logs:  Next exception 'ErrorException' with message 'Undefined index: tag_line_olc (View: /var/www/country-drc/resources/views/layout/partials/head.blade.php)' in /var/www/country-drc/app/Http/Services/SiteService.php:141
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-var-www-country-drc-storage-logs:  #0 /var/www/country-drc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-var-www-country-drc-storage-logs:  Next exception 'ErrorException' with message 'Undefined index: tag_line_olc (View: /var/www/country-drc/resources/views/layout/partials/head.blade.php) (View: /var/www/country-drc/resources/views/layout/partials/head.blade.php)' in /var/www/country-drc/app/Http/Services/SiteService.php:141
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-var-www-country-drc-storage-logs:  #0 /var/www/country-drc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 2)
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-var-www-country-drc-storage-logs:  Next exception 'ErrorException' with message 'Undefined index: tag_line_olc (View: /var/www/country-drc/resources/views/layout/partials/head.blade.php) (View: /var/www/country-drc/resources/views/layout/partials/head.blade.php) (View: /var/www/country-drc/resources/views/layout/partials/head.blade.php)' in /var/www/country-drc/app/Http/Services/SiteService.php:141
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-var-www-country-drc-storage-logs:  #0 /var/www/country-drc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-var-www-country-drc-storage-logs:  #2 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(341): Laravel\Lumen\Application->handleUncaughtException(Object(ErrorException))
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-var-www-country-drc-storage-logs:  #3 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(ErrorException))
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-nginx-error.log:  Stack trace:
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-nginx-error.log:  #0 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(408): Illuminate\View\View->__call('send', Array)
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-nginx-error.log:  #1 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(408): Illuminate\View\View->send()
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-nginx-error.log:  #2 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(341): Laravel\Lumen\Application->handleUncaughtException(Object(ErrorException))
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-nginx-error.log:  #3 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(ErrorException))
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-nginx-error.log:  #4 {main}
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-nginx-error.log:    thrown in /var/www/country-drc/vendor/illuminate/view/View.php on line 392
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-nginx-error.log:  Stack trace:
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-nginx-error.log:  #0 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(408): Illuminate\View\View->__call('send', Array)
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-nginx-error.log:  #1 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(408): Illuminate\View\View->send()
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-nginx-error.log:  #2 /var/www/country-drc/vendor/laravel/lumen-framework/src/Application.php(348): Laravel\Lumen\Application->handleUncaughtException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-nginx-error.log:  #3 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}()
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-nginx-error.log:  #4 {main}
Dec 27 06:13:49 f768bc667662 ecs-rc-subsite-master-nginx-error.log:    thrown in /var/www/country-drc/vendor/illuminate/view/View.php on line 392" while reading response header from upstream, client: ::ffff:10.0.1.156, server: drc.openlandcontracts.org, request: "GET /.well-known/security.txt HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "52.86.151.147"
```

**Comment by adinuca** [comment]
Error messages are available in the logs from the 24th of December.

**Comment by adinuca** [comment]
Hi @man-git007 , @anjesh, please take a look at this issue.

Thank you!

**Comment by anjesh** [comment]
@adinuca i see that http://drc.openlandcontracts.org/ isn't working, i wonder how that error is appearing `/var/www/country-drc/` as it's not being hit from the domain listed here https://github.com/younginnovations/resourcecontracts-rc-subsite/blob/master/config/init.sh#L48

Can you check which domain is hitting that folder `/var/www/country-drc/`?

**Comment by anjesh** [comment]
Also i notice the some suspicious host in the latest log
```
Dec 28 10:37:04 f768bc667662 ecs-rc-subsite-master-nginx-error.log: 
thrown in /var/www/country-drc/vendor/illuminate/view/View.php on line 392" 
while reading response header from upstream, client: ::ffff:10.0.1.156, 
server: drc.openlandcontracts.org, 
request: "POST /passport/captcha/captcha-check HTTP/1.1", 
upstream: "fastcgi://127.0.0.1:9000", 
host: "kyfw.12306.cn", 
referrer: "https://kyfw.12306.cn/otn/leftTicket/init?linktypeid=dc"
```

**Comment by adinuca** [comment]
> @adinuca i see that http://drc.openlandcontracts.org/ isn't working, i wonder how that error is appearing `/var/www/country-drc/` as it's not being hit from the domain listed here https://github.com/younginnovations/resourcecontracts-rc-subsite/blob/master/config/init.sh#L48
> 
> Can you check which domain is hitting that folder `/var/www/country-drc/`?

From this line `export CATEGORY=country-drc
envsubst '$SERVER_NAME $CATEGORY'< ./nginx_subsite.template > /etc/nginx/sites-enabled/country-drc` I would say that any domain name will be heating this

> @adinuca i see that http://drc.openlandcontracts.org/ isn't working, i wonder how that error is appearing `/var/www/country-drc/` as it's not being hit from the domain listed here https://github.com/younginnovations/resourcecontracts-rc-subsite/blob/master/config/init.sh#L48
> 
> Can you check which domain is hitting that folder `/var/www/country-drc/`?

From the nginx config, it looks like only `drc.openlandcontracts.org *.drc.openlandcontracts.org;` should hit that folder.  Because there is no default_server set, any request for which the host does not match the server_name from the nginx configuration files, will be handled by the first nginx config( in this case, the one for drc.openlandcontracts.org). Load balancer is set to handle all requests, no matter the host.

@charlesyoung should https://staging.drc.openlandcontracts.org and  https://drc.opendlandcontracts.org be working?

**Comment by adinuca** [comment]
> Also i notice the some suspicious host in the latest log
> 
> ```
> Dec 28 10:37:04 f768bc667662 ecs-rc-subsite-master-nginx-error.log: 
> thrown in /var/www/country-drc/vendor/illuminate/view/View.php on line 392" 
> while reading response header from upstream, client: ::ffff:10.0.1.156, 
> server: drc.openlandcontracts.org, 
> request: "POST /passport/captcha/captcha-check HTTP/1.1", 
> upstream: "fastcgi://127.0.0.1:9000", 
> host: "kyfw.12306.cn", 
> referrer: "https://kyfw.12306.cn/otn/leftTicket/init?linktypeid=dc"
> ```

This is because the load balancer is handling all requests.

**Comment by man-git007** [comment]
@adinuca we have fixed this undefined index:tag_line_olc and have deployed in staging server.
