### ISSUE TITLE
RC errors in logs

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1204]
## Why
-  Logs are filled with errors when a bot crawls the website. 
- An error is displayed to the user when the path parameter `sortBy` is used without `order` path parameter.

## What
- [x] Source of the issue is found
- [x] A fix is implemented

## Notes
```
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: [2019-07-15 03:40:44] lumen.ERROR: exception 'ErrorException' with message 'Undefined index: order' in /var/www/rc/storage/framework/views/7f4d3758b78edc760d80cdd69a448bdb:76
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: Stack trace:
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/storage/framework/views/7f4d3758b78edc760d80cdd69a448bdb(76): Laravel\Lumen\Application->Laravel\Lumen\{closure}(8, 'Undefined index...', '/var/www/rc/sto...', 76, Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #1 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(42): include('/var/www/rc/sto...')
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #2 /var/www/rc/vendor/illuminate/view/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/rc/sto...', Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #3 /var/www/rc/vendor/illuminate/view/View.php(147): Illuminate\View\Engines\CompilerEngine->get('/var/www/rc/res...', Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #4 /var/www/rc/vendor/illuminate/view/View.php(118): Illuminate\View\View->getContents()
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #5 /var/www/rc/vendor/illuminate/view/View.php(83): Illuminate\View\View->renderContents()
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #6 /var/www/rc/storage/framework/views/61a1d69b629389524d28e65e52660bc6(64): Illuminate\View\View->render()
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #7 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(42): include('/var/www/rc/sto...')
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #8 /var/www/rc/vendor/illuminate/view/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/rc/sto...', Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #9 /var/www/rc/vendor/illuminate/view/View.php(147): Illuminate\View\Engines\CompilerEngine->get('/var/www/rc/res...', Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #10 /var/www/rc/vendor/illuminate/view/View.php(118): Illuminate\View\View->getContents()
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #11 /var/www/rc/vendor/illuminate/view/View.php(83): Illuminate\View\View->renderContents()
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #12 /var/www/rc/vendor/illuminate/http/Response.php(51): Illuminate\View\View->render()
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #13 /var/www/rc/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #14 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1466): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #15 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1412): Laravel\Lumen\Application->prepareResponse(Object(Illuminate\View\View))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #16 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1376): Laravel\Lumen\Application->callControllerCallable(Array, Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #17 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1347): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\CountryController), 'detail', Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #18 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1315): Laravel\Lumen\Application->callControllerAction(Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #19 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1300): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #20 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1270): Laravel\Lumen\Application->handleFoundRoute(Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #21 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1220): Laravel\Lumen\Application->handleDispatcherResponse(Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #22 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #23 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #24 /var/www/rc/app/Http/Middleware/TrustedProxy.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #25 [internal function]: App\Http\Middleware\TrustedProxy->handle(Object(Illuminate\Http\Request), Object(Closure))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #26 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #27 /var/www/rc/app/Http/Middleware/Localization.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #28 [internal function]: App\Http\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #29 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #30 /var/www/rc/vendor/illuminate/session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #31 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #32 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #34 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #35 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1451): Illuminate\Pipeline\Pipeline->then(Object(Closure))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #36 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1221): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #37 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1161): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #38 /var/www/rc/public/index.php(28): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #39 {main}
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/contract_list.blade.php)' in /var/www/rc/storage/framework/views/7f4d3758b78edc760d80cdd69a448bdb:76
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: Stack trace:
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #1 /var/www/rc/vendor/illuminate/view/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/rc/sto...', Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #2 /var/www/rc/vendor/illuminate/view/View.php(147): Illuminate\View\Engines\CompilerEngine->get('/var/www/rc/res...', Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #3 /var/www/rc/vendor/illuminate/view/View.php(118): Illuminate\View\View->getContents()
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #4 /var/www/rc/vendor/illuminate/view/View.php(83): Illuminate\View\View->renderContents()
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #5 /var/www/rc/storage/framework/views/61a1d69b629389524d28e65e52660bc6(64): Illuminate\View\View->render()
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #6 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(42): include('/var/www/rc/sto...')
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #7 /var/www/rc/vendor/illuminate/view/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/rc/sto...', Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #8 /var/www/rc/vendor/illuminate/view/View.php(147): Illuminate\View\Engines\CompilerEngine->get('/var/www/rc/res...', Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #9 /var/www/rc/vendor/illuminate/view/View.php(118): Illuminate\View\View->getContents()
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #10 /var/www/rc/vendor/illuminate/view/View.php(83): Illuminate\View\View->renderContents()
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #11 /var/www/rc/vendor/illuminate/http/Response.php(51): Illuminate\View\View->render()
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #12 /var/www/rc/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #13 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1466): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #14 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1412): Laravel\Lumen\Application->prepareResponse(Object(Illuminate\View\View))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #15 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1376): Laravel\Lumen\Application->callControllerCallable(Array, Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #16 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1347): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\CountryController), 'detail', Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #17 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1315): Laravel\Lumen\Application->callControllerAction(Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #18 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1300): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #19 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1270): Laravel\Lumen\Application->handleFoundRoute(Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #20 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1220): Laravel\Lumen\Application->handleDispatcherResponse(Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #21 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #22 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #23 /var/www/rc/app/Http/Middleware/TrustedProxy.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #24 [internal function]: App\Http\Middleware\TrustedProxy->handle(Object(Illuminate\Http\Request), Object(Closure))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #25 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #26 /var/www/rc/app/Http/Middleware/Localization.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #27 [internal function]: App\Http\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #28 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #29 /var/www/rc/vendor/illuminate/session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #30 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #31 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #32 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #33 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #34 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1451): Illuminate\Pipeline\Pipeline->then(Object(Closure))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #35 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1221): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #36 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1161): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #37 /var/www/rc/public/index.php(28): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #38 {main}
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: Next exception 'ErrorException' with message 'Undefined index: order (View: /var/www/rc/resources/views/contract/partials/contract_list.blade.php) (View: /var/www/rc/resources/views/contract/partials/contract_list.blade.php)' in /var/www/rc/storage/framework/views/7f4d3758b78edc760d80cdd69a448bdb:76
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: Stack trace:
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #0 /var/www/rc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #1 /var/www/rc/vendor/illuminate/view/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/rc/sto...', Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #2 /var/www/rc/vendor/illuminate/view/View.php(147): Illuminate\View\Engines\CompilerEngine->get('/var/www/rc/res...', Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #3 /var/www/rc/vendor/illuminate/view/View.php(118): Illuminate\View\View->getContents()
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #4 /var/www/rc/vendor/illuminate/view/View.php(83): Illuminate\View\View->renderContents()
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #5 /var/www/rc/vendor/illuminate/http/Response.php(51): Illuminate\View\View->render()
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #6 /var/www/rc/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #7 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1466): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #8 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1412): Laravel\Lumen\Application->prepareResponse(Object(Illuminate\View\View))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #9 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1376): Laravel\Lumen\Application->callControllerCallable(Array, Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #10 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1347): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\CountryController), 'detail', Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #11 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1315): Laravel\Lumen\Application->callControllerAction(Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #12 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1300): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #13 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1270): Laravel\Lumen\Application->handleFoundRoute(Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #14 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1220): Laravel\Lumen\Application->handleDispatcherResponse(Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #15 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #16 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #17 /var/www/rc/app/Http/Middleware/TrustedProxy.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #18 [internal function]: App\Http\Middleware\TrustedProxy->handle(Object(Illuminate\Http\Request), Object(Closure))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #19 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #20 /var/www/rc/app/Http/Middleware/Localization.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #21 [internal function]: App\Http\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #22 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #23 /var/www/rc/vendor/illuminate/session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #24 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #25 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #27 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #28 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1451): Illuminate\Pipeline\Pipeline->then(Object(Closure))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #29 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1221): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #30 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1161): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #31 /var/www/rc/public/index.php(28): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-var-www-rc-storage-logs: #32 {main}  
Jul 15 06:40:44 34105bbef178 ecs-rc-subsite-master-nginx-access.log: ::ffff:10.0.0.129 - - [15/Jul/2019:03:40:44 +0000] "GET /countries/cd?page=2&sortby=resource&lang=fr HTTP/1.1" 200 7636 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
```

**Comment by adinuca** [comment]
This exception is encountered when making a request to `/contracts`, using the path parameter `sortBy` without using the `order` path parameter.

**Comment by adinuca** [comment]
This has been deployed.
