### ISSUE TITLE
Handle 404 gracefully 

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1205]
## Why
 When a page is not found for resourcecontracts.org, logs are generated. This makes debugging for real problems harder.

## What
- [x] No stacktrace is generated when a page is not found

## Notes
Logs generated now: 
```
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-error.log: 2019/08/12 03:58:33 [error] 34#34: *523211 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'BadMethodCallException' with message 'Method [send] does not exist on view.' in /var/www/rc/vendor/illuminate/view/View.php:392
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-error.log: Stack trace:
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-error.log: #0 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(408): Illuminate\View\View->__call('send', Array)
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-error.log: #1 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(408): Illuminate\View\View->send()
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-error.log: #2 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(341): Laravel\Lumen\Application->handleUncaughtException(Object(ErrorException))
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-error.log: #3 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(ErrorException))
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-error.log: #4 {main}
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-error.log:   thrown in /var/www/rc/vendor/illuminate/view/View.php on line 392
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-error.log: PHP message: PHP Fatal error:  Uncaught exception 'BadMethodCallException' with message 'Method [send] does not exist on view.' in /var/www/rc/vendor/illuminate/view/View.php:392
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-error.log: Stack trace:
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-error.log: #0 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(408): Illuminate\View\View->__call('send', Array)
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-error.log: #1 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(408): Illuminate\View\View->send()
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-error.log: #2 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(348): Laravel\Lumen\Application->handleUncaughtException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-error.log: #3 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}()
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-error.log: #4 {main}
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-error.log:   thrown in /var/www/rc/vendor/illuminate/view/View.php on line 392" while reading response header from upstream, client: ::ffff:10.0.0.129, server: www.resourcecontracts.org, request: "GET /robots.txt HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "resourcecontracts.org"



```

**Comment by adinuca** [comment]
404 is handled correctly, even so, the robots.txt sometimes returns 500
```
Aug 08 21:44:05 5744e87bd9a0 ecs-rc-subsite-master-nginx-access.log: ::ffff:10.0.1.156 - - [08/Aug/2019:18:44:05 +0000] "GET /robots.txt HTTP/1.1" 500 5 "-" "Mozilla/5.0 (compatible; SemrushBot/3~bl; +http://www.semrush.com/bot.html)"
Aug 08 21:44:25 5744e87bd9a0 ecs-rc-subsite-master-nginx-access.log: ::ffff:10.0.0.129 - - [08/Aug/2019:18:44:25 +0000] "GET /robots.txt HTTP/1.1" 500 5 "-" "Mozilla/5.0 (compatible; SemrushBot/3~bl; +http://www.semrush.com/bot.html)"
Aug 08 21:45:24 5744e87bd9a0 ecs-rc-subsite-master-nginx-access.log: ::ffff:10.0.0.129 - - [08/Aug/2019:18:45:24 +0000] "GET /robots.txt HTTP/1.1" 500 5 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
Aug 08 21:46:34 5744e87bd9a0 ecs-rc-subsite-master-nginx-access.log: ::ffff:10.0.0.129 - - [08/Aug/2019:18:46:34 +0000] "GET /robots.txt HTTP/1.1" 500 5 "-" "Mozilla/5.0 (compatible; Daum/4.1; +http://cs.daum.net/faq/15/4118.html?faqId=28966)"
Aug 08 21:46:54 5744e87bd9a0 ecs-rc-subsite-master-nginx-access.log: ::ffff:10.0.0.129 - - [08/Aug/2019:18:46:54 +0000] "GET /robots.txt HTTP/1.1" 500 5 "-" "Mozilla/5.0 (compatible; SemrushBot/3~bl; +http://www.semrush.com/bot.html)"
Aug 10 02:39:38 3fb1df340d4f ecs-rc-subsite-master-nginx-access.log: ::ffff:10.0.0.129 - - [09/Aug/2019:23:39:38 +0000] "GET /robots.txt HTTP/1.1" 500 5 "-" "Gigabot"
Aug 10 02:41:39 3fb1df340d4f ecs-rc-subsite-master-nginx-access.log: ::ffff:10.0.1.156 - - [09/Aug/2019:23:41:39 +0000] "GET /robots.txt HTTP/1.1" 500 5 "-" "Mozilla/5.0 (compatible; SemrushBot/3~bl; +http://www.semrush.com/bot.html)"
Aug 10 12:18:04 5744e87bd9a0 ecs-rc-subsite-master-nginx-access.log:  ::ffff:10.0.0.129 - - [10/Aug/2019:09:18:04 +0000] "GET /robots.txt HTTP/1.1" 500 5 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
Aug 10 12:18:11 5744e87bd9a0 ecs-rc-subsite-master-nginx-access.log:  ::ffff:10.0.0.129 - - [10/Aug/2019:09:18:11 +0000] "GET /robots.txt HTTP/1.1" 500 5 "-" "Mozilla/5.0 (compatible; DotBot/1.1; http://www.opensiteexplorer.org/dotbot, help@moz.com)"
Aug 10 12:18:12 5744e87bd9a0 ecs-rc-subsite-master-nginx-access.log:  ::ffff:10.0.0.129 - - [10/Aug/2019:09:18:12 +0000] "GET /robots.txt HTTP/1.1" 500 5 "-" "Mozilla/5.0 (compatible; DotBot/1.1; http://www.opensiteexplorer.org/dotbot, help@moz.com)"
Aug 12 06:58:33 5744e87bd9a0 ecs-rc-subsite-master-nginx-access.log:  ::ffff:10.0.0.129 - - [12/Aug/2019:03:58:33 +0000] "GET /robots.txt HTTP/1.1" 500 5 "-" "Gigabot"
```

ELB logs suggest this is resourcecontracts.org

**Comment by adinuca** [comment]
Pingdom did not detect any downtime to suggest the application was having issues.

**Comment by adinuca** [comment]
404 is handled correctly. The issue might be that the application is crawled by bots which overwhelm the app. We will know more after that investigation is completed.
