### ISSUE TITLE
Investigate error logs from RC 

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1206]
## Why
Error logs can hide problems with the application.

## What
- [ ] The cause of the logs is determined
- [ ] An issue is raised to fix it if it cannot be fixed in less than 3h. 

## Notes
```
Aug 12 07:02:03 91c60b36db8a ecs-rc-api-master-apache2.log: 10.0.1.184 - - [12/Aug/2019:04:02:03 +0000] "GET /contract/2305/annotations?category=olc HTTP/1.1" 200 321 "-" "-"
Aug 12 07:02:03 17bba588da7b ecs-rc-api-master-apache2.log: 10.0.1.184 - - [12/Aug/2019:04:02:03 +0000] "GET /contract/2867/annotations?country_code=gn&is_country_site=1&category=rc HTTP/1.1" 200 321 "-" "-"
Aug 12 07:02:03 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: [2019-08-12 04:02:03] lumen.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/country-gn/app/Http/Services/APIService.php:167
Aug 12 07:02:03 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: Stack trace:
Aug 12 07:02:03 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #0 /var/www/country-gn/app/Http/Services/APIService.php(167): Laravel\Lumen\Application->Laravel\Lumen\{closure}(8, 'Trying to get p...', '/var/www/countr...', 167, Array)
Aug 12 07:02:03 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #1 /var/www/country-gn/storage/framework/views/2baed56d87f635473ce9f1f1dab2972d(57): App\Http\Services\APIService->getAnnotations(2813)
Aug 12 07:02:03 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #2 /var/www/country-gn/vendor/illuminate/view/Engines/PhpEngine.php(42): include('/var/www/countr...')
Aug 12 07:02:03 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #3 /var/www/country-gn/vendor/illuminate/view/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/countr...', Array)
Aug 12 07:02:03 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #4 /var/www/country-gn/vendor/illuminate/view/View.php(147): Illuminate\View\Engines\CompilerEngine->get('/var/www/countr...', Array)
Aug 12 07:02:03 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #5 /var/www/country-gn/vendor/illuminate/view/View.php(118): Illuminate\View\View->getContents()
Aug 12 07:02:03 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #6 /var/www/country-gn/vendor/illuminate/view/View.php(83): Illuminate\View\View->renderContents()
Aug 12 07:02:03 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #7 /var/www/country-gn/storage/framework/views/835077784351b6674acf9b625cf8b7a3(56): Illuminate\View\View->render()
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #8 /var/www/country-gn/vendor/illuminate/view/Engines/PhpEngine.php(42): include('/var/www/countr...')
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #9 /var/www/country-gn/vendor/illuminate/view/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/countr...', Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #10 /var/www/country-gn/vendor/illuminate/view/View.php(147): Illuminate\View\Engines\CompilerEngine->get('/var/www/countr...', Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #11 /var/www/country-gn/vendor/illuminate/view/View.php(118): Illuminate\View\View->getContents()
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #12 /var/www/country-gn/vendor/illuminate/view/View.php(83): Illuminate\View\View->renderContents()
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #13 /var/www/country-gn/vendor/illuminate/http/Response.php(51): Illuminate\View\View->render()
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #14 /var/www/country-gn/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #15 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1466): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #16 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1412): Laravel\Lumen\Application->prepareResponse(Object(Illuminate\View\View))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #17 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1376): Laravel\Lumen\Application->callControllerCallable(Array, Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #18 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1347): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\Contract\ContractController), 'index', Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #19 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1315): Laravel\Lumen\Application->callControllerAction(Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #20 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1300): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #21 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1215): Laravel\Lumen\Application->handleFoundRoute(Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #22 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #23 /var/www/country-gn/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs: #24 /var/www/country-gn/app/Http/Middleware/TrustedProxy.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #25 [internal function]: App\Http\Middleware\TrustedProxy->handle(Object(Illuminate\Http\Request), Object(Closure))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #26 /var/www/country-gn/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #27 /var/www/country-gn/app/Http/Middleware/Localization.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #28 [internal function]: App\Http\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #29 /var/www/country-gn/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #30 /var/www/country-gn/vendor/illuminate/session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #31 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
Aug 12 07:02:04 91c60b36db8a ecs-rc-api-master-apache2.log:  10.0.1.184 - - [12/Aug/2019:04:02:03 +0000] "GET /contract/3085/annotations?category=olc HTTP/1.1" 200 321 "-" "-"
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #32 /var/www/country-gn/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #34 /var/www/country-gn/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #35 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1451): Illuminate\Pipeline\Pipeline->then(Object(Closure))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #36 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1221): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #37 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1161): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #38 /var/www/country-gn/public/index.php(28): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #39 {main}
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /var/www/country-gn/resources/views/contract/partials/search_list.blade.php)' in /var/www/country-gn/app/Http/Services/APIService.php:167
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  Stack trace:
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #0 /var/www/country-gn/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 3)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #1 /var/www/country-gn/vendor/illuminate/view/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/countr...', Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #2 /var/www/country-gn/vendor/illuminate/view/View.php(147): Illuminate\View\Engines\CompilerEngine->get('/var/www/countr...', Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #3 /var/www/country-gn/vendor/illuminate/view/View.php(118): Illuminate\View\View->getContents()
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #4 /var/www/country-gn/vendor/illuminate/view/View.php(83): Illuminate\View\View->renderContents()
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #5 /var/www/country-gn/storage/framework/views/835077784351b6674acf9b625cf8b7a3(56): Illuminate\View\View->render()
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #6 /var/www/country-gn/vendor/illuminate/view/Engines/PhpEngine.php(42): include('/var/www/countr...')
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #7 /var/www/country-gn/vendor/illuminate/view/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/countr...', Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #8 /var/www/country-gn/vendor/illuminate/view/View.php(147): Illuminate\View\Engines\CompilerEngine->get('/var/www/countr...', Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #9 /var/www/country-gn/vendor/illuminate/view/View.php(118): Illuminate\View\View->getContents()
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #10 /var/www/country-gn/vendor/illuminate/view/View.php(83): Illuminate\View\View->renderContents()
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #11 /var/www/country-gn/vendor/illuminate/http/Response.php(51): Illuminate\View\View->render()
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #12 /var/www/country-gn/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #13 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1466): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #14 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1412): Laravel\Lumen\Application->prepareResponse(Object(Illuminate\View\View))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #15 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1376): Laravel\Lumen\Application->callControllerCallable(Array, Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #16 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1347): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\Contract\ContractController), 'index', Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #17 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1315): Laravel\Lumen\Application->callControllerAction(Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #18 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1300): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #19 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1215): Laravel\Lumen\Application->handleFoundRoute(Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #20 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #21 /var/www/country-gn/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #22 /var/www/country-gn/app/Http/Middleware/TrustedProxy.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #23 [internal function]: App\Http\Middleware\TrustedProxy->handle(Object(Illuminate\Http\Request), Object(Closure))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #24 /var/www/country-gn/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #25 /var/www/country-gn/app/Http/Middleware/Localization.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #26 [internal function]: App\Http\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #27 /var/www/country-gn/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #28 /var/www/country-gn/vendor/illuminate/session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #29 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #30 /var/www/country-gn/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #32 /var/www/country-gn/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #33 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1451): Illuminate\Pipeline\Pipeline->then(Object(Closure))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #34 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1221): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #35 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1161): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #36 /var/www/country-gn/public/index.php(28): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #37 {main}
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /var/www/country-gn/resources/views/contract/partials/search_list.blade.php) (View: /var/www/country-gn/resources/views/contract/partials/search_list.blade.php)' in /var/www/country-gn/app/Http/Services/APIService.php:167
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  Stack trace:
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #0 /var/www/country-gn/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #1 /var/www/country-gn/vendor/illuminate/view/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/countr...', Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #2 /var/www/country-gn/vendor/illuminate/view/View.php(147): Illuminate\View\Engines\CompilerEngine->get('/var/www/countr...', Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #3 /var/www/country-gn/vendor/illuminate/view/View.php(118): Illuminate\View\View->getContents()
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #4 /var/www/country-gn/vendor/illuminate/view/View.php(83): Illuminate\View\View->renderContents()
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #5 /var/www/country-gn/vendor/illuminate/http/Response.php(51): Illuminate\View\View->render()
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #6 /var/www/country-gn/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #7 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1466): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #8 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1412): Laravel\Lumen\Application->prepareResponse(Object(Illuminate\View\View))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #9 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1376): Laravel\Lumen\Application->callControllerCallable(Array, Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #10 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1347): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\Contract\ContractController), 'index', Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #11 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1315): Laravel\Lumen\Application->callControllerAction(Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #12 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1300): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #13 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1215): Laravel\Lumen\Application->handleFoundRoute(Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #14 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #15 /var/www/country-gn/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #16 /var/www/country-gn/app/Http/Middleware/TrustedProxy.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #17 [internal function]: App\Http\Middleware\TrustedProxy->handle(Object(Illuminate\Http\Request), Object(Closure))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #18 /var/www/country-gn/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #19 /var/www/country-gn/app/Http/Middleware/Localization.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #20 [internal function]: App\Http\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #21 /var/www/country-gn/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #22 /var/www/country-gn/vendor/illuminate/session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #23 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #24 /var/www/country-gn/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #26 /var/www/country-gn/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #27 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1451): Illuminate\Pipeline\Pipeline->then(Object(Closure))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #28 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1221): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #29 /var/www/country-gn/vendor/laravel/lumen-framework/src/Application.php(1161): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #30 /var/www/country-gn/public/index.php(28): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
Aug 12 07:02:04 5744e87bd9a0 ecs-rc-subsite-master-var-www-country-gn-storage-logs:  #31 {main}  
Aug 12 07:02:04 17bba588da7b ecs-rc-api-master-apache2.log:  10.0.1.184 - - [12/Aug/2019:04:02:04 +0000] "GET /contract/3084/annotations?category=olc HTTP/1.1" 200 321 "-" "-"
```

**Comment by adinuca** [comment]
This happens when the API returns an error. It can be closed.
