### ISSUE TITLE
ResourceContract Admin site has error - https://admin.resourcecontracts.org/mturk/4117/31865

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1287]
@adinuca commented on [Fri Apr 24 2020](https://github.com/NRGI/nrgi-dcos/issues/527)

## Why
This error has started occurring recently. 

## What
- [ ] The error no longer appears 

## Notes
```
Url: https://u3074154.ct.sendgrid.net/ls/click?upn=2wcFhx-2BC6mwDQkGE7SAjtZH-2FcC1Y99QfAUcJQHwk1Tvt8b6MpCcfTnwRMSH1-2BcA42K0x0aMF-2Bo7Si1U5QPjV-2Fg-3D-3DycwL_H2TPIH0jjrBoa9qiMpAJugSdb2jMB-2FG1FEKYZo9GqtYCkl1Yiyp8PBDKLeuCIoqhkUDl06nD9ZycpGdAhl7Z1B-2FiKuAvqTEevPjdcRhn3uwMVGnULPahnf4vulw3wQuXgRlfWMaViLYY7h0THD9dcdFYDUF2B4HhfS0Ul6Tevz22gMfqk06CQ7rBXfreNW1lEeeI4Tu8PC2IfKiCUJJEwQELSVU0zLpCT2LYcBoQd4vqqyN6CYXTNt9xdi8TIfJT 

Request: {"request":[],"server":{"REDIRECT_STATUS":"200","HTTP_X_FORWARDED_FOR":"73.86.43.145","HTTP_X_FORWARDED_PROTO":"https","HTTP_X_FORWARDED_PORT":"443","HTTP_HOST":"admin.resourcecontracts.org","HTTP_X_AMZN_TRACE_ID":"Root=1-5ea21f63-b2457f5fce09311892b36daf","HTTP_UPGRADE_INSECURE_REQUESTS":"1","HTTP_USER_AGENT":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/81.0.4044.113 Safari\/537.36","HTTP_ACCEPT":"text\/html,application\/xhtml+xml,application\/xml;q=0.9,image\/webp,image\/apng,*\/*;q=0.8,application\/signed-exchange;v=b3;q=0.9","HTTP_SEC_FETCH_SITE":"same-origin","HTTP_SEC_FETCH_MODE":"navigate","HTTP_SEC_FETCH_USER":"?1","HTTP_SEC_FETCH_DEST":"document","HTTP_REFERER":"https:\/\/admin.resourcecontracts.org\/mturk\/4117?status=1&approved=0","HTTP_ACCEPT_ENCODING":"gzip, deflate, br","HTTP_ACCEPT_LANGUAGE":"en-US,en;q=0.9","HTTP_COOKIE":"rc_admin_lang=en; remember_82e5d2c56bdd0811318f0cf078b78bfc=eyJpdiI6Im5vNlQ4YTllcmhsSVphcVUyQmVzcVE9PSIsInZhbHVlIjoiaSt4a0lPeTRpS1NndVBaWDlWd0V4NDhoK1phVmY2eDdid3p2ZXVLYUFBU2NsdjBvaUM3b3gzNXJIdDNZcGxFbFFKeWZzMUhBZXh6QWFUUzRSaWdnQkoyRElFYXdXTXRCa2lmamJvck0wdVU9IiwibWFjIjoiMzNiYWU5MDI3OTVhODRjNmIwMDJhN2IzNGU0NTA2YjQ0MWEzOGMxZDk0NDlkZjRiZTY5MjlkOWUxZmY2Mzg4NyJ9; _ga=GA1.2.232573640.1575796166; AWSALB=EwvZqnfWx2L3PYFykeFNMJcvcE4mpoka3fSTAf2ptT95uQKFebuhdnei54Pxgftz00LV41gGnBcqKp6eccrRJrQX2FQ6\/iUWAtjThXtWMAaSdOWfSqb8uVpvB79K; AWSALBCORS=EwvZqnfWx2L3PYFykeFNMJcvcE4mpoka3fSTAf2ptT95uQKFebuhdnei54Pxgftz00LV41gGnBcqKp6eccrRJrQX2FQ6\/iUWAtjThXtWMAaSdOWfSqb8uVpvB79K; XSRF-TOKEN=eyJpdiI6IjZESGJLbkZWSnBEQzNPMitGUDJmTEE9PSIsInZhbHVlIjoiT29uQWhqaGVtWm9DYWdMZ2pqUVN0WDlTRngwQXBvK2hYc3d2bzBOTnZ1ekNFUkxCd09NRG55NUNqVGhnMHNscUFcL3JudDJENHVmRkhCbkZxdkNPem1nPT0iLCJtYWMiOiIwOTRlYzI1MWY5ZWY3N2I0ZWI5MDI2Y2I2MDg4NTliNDZjOGMxZDY3YmUwMWNkNmE2NTgyMGYxNDE0ZTA2ZDc2In0%3D; laravel_session=eyJpdiI6IkcyNXh2ZnpEdEJXcnRiN2szNzdIQnc9PSIsInZhbHVlIjoiXC92KzB6SDNTQU94Nk16MXNlMFhpR3QxRXFDNkU4YlVuUkJBMlVONUdtMGtFMkxXM2ZTb2w0alwvMzFabE43SFBrY3FMMmdpeUZIWmozS1hQZmM2SnJlZz09IiwibWFjIjoiZjg4YThhMDliNTY3MTM4YThlMzBkNjNiODU1ZjIyYjU2MWQ2YWE5YzgxM2I3MGI5Mzg3ZDQ4ZWNjMmQ3Y2JkZiJ9","PATH":"\/usr\/local\/sbin:\/usr\/local\/bin:\/usr\/sbin:\/usr\/bin:\/sbin:\/bin","SERVER_SIGNATURE":"<address>Apache\/2.4.7 (Ubuntu) Server at admin.resourcecontracts.org Port 80<\/address>\n","SERVER_SOFTWARE":"Apache\/2.4.7 (Ubuntu)","SERVER_NAME":"admin.resourcecontracts.org","SERVER_ADDR":"172.17.0.8","SERVER_PORT":"80","REMOTE_ADDR":"10.0.0.88","DOCUMENT_ROOT":"\/var\/www\/rc-admin\/public","REQUEST_SCHEME":"http","CONTEXT_PREFIX":"","CONTEXT_DOCUMENT_ROOT":"\/var\/www\/rc-admin\/public","SERVER_ADMIN":"webmaster@admin.resourcecontracts.org","SCRIPT_FILENAME":"\/var\/www\/rc-admin\/public\/index.php","REMOTE_PORT":"1548","REDIRECT_URL":"\/mturk\/4117\/31865","GATEWAY_INTERFACE":"CGI\/1.1","SERVER_PROTOCOL":"HTTP\/1.1","REQUEST_METHOD":"GET","QUERY_STRING":"","REQUEST_URI":"\/mturk\/4117\/31865","SCRIPT_NAME":"\/index.php","PHP_SELF":"\/index.php","REQUEST_TIME_FLOAT":1587683171.019,"REQUEST_TIME":1587683171}} 

Error: Undefined offset: 0 

Log: exception 'ErrorException' with message 'Undefined offset: 0' in /var/www/rc-admin/app/Nrgi/Mturk/Services/MTurkService.php:211
Stack trace:
#0 /var/www/rc-admin/app/Nrgi/Mturk/Services/MTurkService.php(211): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined offse...', '/var/www/rc-adm...', 211, Array)
#1 /var/www/rc-admin/app/Nrgi/Mturk/Controllers/MTurkController.php(135): App\Nrgi\Mturk\Services\MTurkService->getAns(Object(App\Nrgi\Mturk\Entities\Task))
#2 [internal function]: App\Nrgi\Mturk\Controllers\MTurkController->taskDetail('4117', '31865')
#3 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(246): call_user_func_array(Array, Array)
#4 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(162): Illuminate\Routing\Controller->callAction('taskDetail', Array)
#5 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(107): Illuminate\Routing\ControllerDispatcher->call(Object(App\Nrgi\Mturk\Controllers\MTurkController), Object(Illuminate\Routing\Route), 'taskDetail')
#6 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#7 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#8 /var/www/rc-admin/app/Http/Middleware/Authenticate.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Nrgi\Mturk\Controllers\MTurkController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'taskDetail')
#14 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Nrgi\Mturk\...', 'taskDetail')
#15 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#16 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(701): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#23 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#24 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 /var/www/rc-admin/app/Http/Middleware/Localization.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/rc-admin/app/Http/Middleware/VerifyCsrfToken.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#44 /var/www/rc-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#45 /var/www/rc-admin/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#46 {main}
```

**Comment by adinuca** [comment]
@charlesyoung , this is a recent issue. Can YIPL have a look?
Thank you.

**Comment by charlesyoung** [comment]
Thanks @adinuca 

@man-git007 is this possibly related to [#1266?]([url](https://github.com/NRGI/resourcecontracts.org/issues/1266))

**Comment by man-git007** [comment]
@charlesyoung The worker has submitted the hit `3VI0PC2ZAY8YBBN21000JGJ7CP0OXV` with no answer. Therefore it's causing the error in the admin side. I suggest the hit to be rejected and then reset it. For your assistance, I have attached a screenshot of the log.
![Screenshot from 2020-04-29 12-14-33](https://user-images.githubusercontent.com/23434972/80566693-48495a80-8a13-11ea-993d-e8e26951f94d.png)
