### ISSUE TITLE
New Papertrail error - 'array_key_exists(): The first argument should be either a string or an integer'

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1293]
## Why
New error in the logs. 

## What
- [ ] Cause of the error logs is found
- [ ] The issue is fixed 
## Notes
```
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: [2020-05-18 22:03:38] lumen.ERROR: exception 'ErrorException' with message 'array_key_exists(): The first argument should be either a string or an integer' in /var/www/olc/app/Http/Services/LocalizationService.php:84
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: Stack trace:
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: #0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(2, 'array_key_exist...', '/var/www/olc/ap...', 84, Array)
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: #1 /var/www/olc/app/Http/Services/LocalizationService.php(84): array_key_exists(false, Array)
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: #2 /var/www/olc/app/Http/Services/LocalizationService.php(58): App\Http\Services\LocalizationService->getLanguage()
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: #3 /var/www/olc/app/Http/Middleware/Localization.php(35): App\Http\Services\LocalizationService->setup()
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: #4 [internal function]: App\Http\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: #5 /var/www/olc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: #6 /var/www/olc/vendor/illuminate/session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: #7 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: #8 /var/www/olc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: #9 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: #10 /var/www/olc/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: #11 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1451): Illuminate\Pipeline\Pipeline->then(Object(Closure))
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: #12 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1221): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: #13 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1161): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: #14 /var/www/olc/public/index.php(28): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
May 19 01:03:38 cadaa19ae0da ecs-rc-subsite-master-var-www-olc-storage-logs: #15 {main}  
```

**Comment by adinuca** [comment]
Hi @charlesyoung, this error started occurring on the 19th. Could YIPL have a look?

**Comment by anjesh** [comment]
~ 4-5 hours to see where these errors are coming from, and fix
