### ISSUE TITLE
Exception in logs: Undefined property: stdClass::$result_total

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1300]
## Why
This error has started appearing in the logs for OLC on the 20th of June.

## What
- [ ] Cause of the errors is determined and fixed. 

## Notes
This reproduces when trying to view the last page of results for some searches:
- first page works: https://guinea.resourcecontracts.org/search/group?order=desc&sortby=resource
- last page crashes: https://guinea.resourcecontracts.org/search/group?order=desc&sortby=resource&page=5

Here is a sample stack trace from logs:

```
Jun 23 06:20:41 d2d518a6f2f3 ecs-rc-api-master-elasticsearch.log: [2020-06-23 03:20:41] log.WARNING: Request Failure: {"method":"GET","uri":"https://a71984c978ba40b6aff596fed0709018.us-east-1.aws.found.io:9243/rc_live_5/master/_search","headers":{"Host":["a71984c978ba40b6aff596fed0709018.us-east-1.aws.found.io:9243"],"Content-Type":["application/json"],"Accept":["application/json"]},"HTTP code":400,"duration":0.013309,"error":"{\"error\":{\"root_cause\":[{\"type\":\"query_shard_exception\",\"reason\":\"No mapping found for [fr.contract_name.keyword] in order to sort on\",\"index_uuid\":\"qTFOjW6ISQmNr0wcY97z-Q\",\"index\":\"rc_live_5\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"rc_live_5\",\"node\":\"7J6zazp3SIyqdgTk-hg3-Q\",\"reason\":{\"type\":\"query_shard_exception\",\"reason\":\"No mapping found for [fr.contract_name.keyword] in order to sort on\",\"index_uuid\":\"qTFOjW6ISQmNr0wcY97z-Q\",\"index\":\"rc_live_5\"}}]},\"status\":400}"} []
Jun 23 06:20:41 d2d518a6f2f3 ecs-rc-api-master-elasticsearch.log: [2020-06-23 03:20:41] log.WARNING: Response ["{\"error\":{\"root_cause\":[{\"type\":\"query_shard_exception\",\"reason\":\"No mapping found for [fr.contract_name.keyword] in order to sort on\",\"index_uuid\":\"qTFOjW6ISQmNr0wcY97z-Q\",\"index\":\"rc_live_5\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"rc_live_5\",\"node\":\"7J6zazp3SIyqdgTk-hg3-Q\",\"reason\":{\"type\":\"query_shard_exception\",\"reason\":\"No mapping found for [fr.contract_name.keyword] in order to sort on\",\"index_uuid\":\"qTFOjW6ISQmNr0wcY97z-Q\",\"index\":\"rc_live_5\"}}]},\"status\":400}"] []
Jun 23 06:20:41 d2d518a6f2f3 ecs-rc-api-master-apache2.log: 10.0.1.210 - - [23/Jun/2020:03:20:41 +0000] "GET /contracts/group?q=&country_code&corporate_group&company_name&contract_type&document_type&language&year&resource&group=metadata%7Ctext%7Cannotations&annotation_category&sort_by=contract_name&order=asc&per_page=10&from=150&all=0&download=&annotated=&lang=fr&category=olc HTTP/1.1" 200 386 "-" "-"
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: [2020-06-23 03:20:41] lumen.ERROR: exception 'ErrorException' with message 'Undefined property: stdClass::$result_total' in /var/www/olc/storage/framework/views/02fe53d0577e8a8282e9191bbd50f93c:77
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: Stack trace:
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #0 /var/www/olc/storage/framework/views/02fe53d0577e8a8282e9191bbd50f93c(77): Laravel\Lumen\Application->Laravel\Lumen\{closure}(8, 'Undefined prope...', '/var/www/olc/st...', 77, Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #1 /var/www/olc/vendor/illuminate/view/Engines/PhpEngine.php(42): include('/var/www/olc/st...')
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #2 /var/www/olc/vendor/illuminate/view/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/olc/st...', Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #3 /var/www/olc/vendor/illuminate/view/View.php(147): Illuminate\View\Engines\CompilerEngine->get('/var/www/olc/re...', Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #4 /var/www/olc/vendor/illuminate/view/View.php(118): Illuminate\View\View->getContents()
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #5 /var/www/olc/vendor/illuminate/view/View.php(83): Illuminate\View\View->renderContents()
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #6 /var/www/olc/vendor/illuminate/http/Response.php(51): Illuminate\View\View->render()
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #7 /var/www/olc/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #8 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1466): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #9 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1412): Laravel\Lumen\Application->prepareResponse(Object(Illuminate\View\View))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #10 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1351): Laravel\Lumen\Application->callControllerCallable(Array, Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #11 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1315): Laravel\Lumen\Application->callControllerAction(Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #12 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1300): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #13 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1215): Laravel\Lumen\Application->handleFoundRoute(Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #14 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #15 /var/www/olc/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #16 /var/www/olc/app/Http/Middleware/TrustedProxy.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #17 [internal function]: App\Http\Middleware\TrustedProxy->handle(Object(Illuminate\Http\Request), Object(Closure))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #18 /var/www/olc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #19 /var/www/olc/app/Http/Middleware/Localization.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #20 [internal function]: App\Http\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #21 /var/www/olc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #22 /var/www/olc/vendor/illuminate/session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #23 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #24 /var/www/olc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #26 /var/www/olc/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #27 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1451): Illuminate\Pipeline\Pipeline->then(Object(Closure))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #28 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1221): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #29 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1161): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #30 /var/www/olc/public/index.php(28): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #31 {main}
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: Next exception 'ErrorException' with message 'Undefined property: stdClass::$result_total (View: /var/www/olc/resources/views/site/groupDemo.blade.php)' in /var/www/olc/storage/framework/views/02fe53d0577e8a8282e9191bbd50f93c:77
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: Stack trace:
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #0 /var/www/olc/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #1 /var/www/olc/vendor/illuminate/view/Engines/CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/olc/st...', Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #2 /var/www/olc/vendor/illuminate/view/View.php(147): Illuminate\View\Engines\CompilerEngine->get('/var/www/olc/re...', Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #3 /var/www/olc/vendor/illuminate/view/View.php(118): Illuminate\View\View->getContents()
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #4 /var/www/olc/vendor/illuminate/view/View.php(83): Illuminate\View\View->renderContents()
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #5 /var/www/olc/vendor/illuminate/http/Response.php(51): Illuminate\View\View->render()
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #6 /var/www/olc/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #7 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1466): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #8 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1412): Laravel\Lumen\Application->prepareResponse(Object(Illuminate\View\View))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #9 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1351): Laravel\Lumen\Application->callControllerCallable(Array, Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #10 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1315): Laravel\Lumen\Application->callControllerAction(Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #11 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1300): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #12 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1215): Laravel\Lumen\Application->handleFoundRoute(Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #13 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #14 /var/www/olc/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #15 /var/www/olc/app/Http/Middleware/TrustedProxy.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #16 [internal function]: App\Http\Middleware\TrustedProxy->handle(Object(Illuminate\Http\Request), Object(Closure))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #17 /var/www/olc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #18 /var/www/olc/app/Http/Middleware/Localization.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #19 [internal function]: App\Http\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #20 /var/www/olc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #21 /var/www/olc/vendor/illuminate/session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #22 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #23 /var/www/olc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #24 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #25 /var/www/olc/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #26 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1451): Illuminate\Pipeline\Pipeline->then(Object(Closure))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #27 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1221): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #28 /var/www/olc/vendor/laravel/lumen-framework/src/Application.php(1161): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #29 /var/www/olc/public/index.php(28): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
Jun 23 06:20:41 6fc5a887bcac ecs-rc-subsite-master-var-www-olc-storage-logs: #30 {main}  
```

**Comment by adinuca** [comment]
Hi @charlesyoung , could YIPL have a look at this? It is a recent error.

**Comment by iprunache** [comment]
@charlesyoung we get a lot of these errors daily from search bots trying to index subsites. It makes it difficult to monitor for other errors with greater impact. Would there be some availability from YIPL to look at it?

**Comment by iprunache** [comment]
It looks like we just need to replace `$contracts->result_total` with `$contracts->total` in `groupDemo.blade.php`.

**Comment by charlesyoung** [comment]
Many thanks @iprunache

**Comment by iprunache** [comment]
@charlesyoung it took longer that planned but most of this is now fixed. I'm still seeing some isolated errors which must come from a different use case. I'll open another issue if we need to handle those too.

**Comment by charlesyoung** [comment]
Many thanks @iprunache
