### ISSUE TITLE
www.mines-rdc.cd/resourcecontracts/ throws error 500

### ISSUE THREAD

**Issue by iprunache** [NRGI/resourcecontracts.org#1316]
## Why
The IMF is in the DRC and contract transparency is key in the government getting a loan and the site is one way of showing this. We need the site up.

## What
- [ ] code that works with the DRC database is deployed to the mines-rdc.cd server

## Notes
The server runs this version of the subsite:
```
commit d4cff6fca540e3ed50f3c4594184ed6a9961bf88 (HEAD -> master, origin/master, origin/HEAD)
Merge: 4702fbb 1d68876
Author: Manish Pradhan <knowme466@gmail.com>
Date:   Thu Jul 30 16:48:40 2020 +0545
```

This is what I found in the `lumen.log` on the server:
```
[2020-08-21 10:50:19] lumen.ERROR: ErrorException: compact(): Undefined variable: total_contract in /home/mines/public_html/resourcecontracts/app/Http/Controllers/FilterController.php:50
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(8, 'compact(): Unde...', '/home/mines/pub...', 50, Array)
#1 /home/mines/public_html/resourcecontracts/app/Http/Controllers/FilterController.php(50): compact('contracts', 'filter', 'total_contract', 'currentPage', 'meta')
#2 [internal function]: App\Http\Controllers\FilterController->index(Object(Illuminate\Http\Request))
#3 /home/mines/public_html/resourcecontracts/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#4 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1411): Illuminate\Container\Container->call(Array, Array)
#5 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1350): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#6 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1315): Laravel\Lumen\Application->callControllerAction(Array)
#7 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1300): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#8 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1215): Laravel\Lumen\Application->handleFoundRoute(Array)
#9 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(Illuminate\Http\Request))
#10 /home/mines/public_html/resourcecontracts/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 /home/mines/public_html/resourcecontracts/app/Http/Middleware/TrustedProxy.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 [internal function]: App\Http\Middleware\TrustedProxy->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /home/mines/public_html/resourcecontracts/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#14 /home/mines/public_html/resourcecontracts/app/Http/Middleware/Localization.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 [internal function]: App\Http\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /home/mines/public_html/resourcecontracts/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#17 /home/mines/public_html/resourcecontracts/vendor/illuminate/session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /home/mines/public_html/resourcecontracts/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /home/mines/public_html/resourcecontracts/vendor/illuminate/pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1451): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1221): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#24 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1161): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#25 /home/mines/public_html/resourcecontracts/index.php(28): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#26 {main}
[2020-08-21 10:50:19] lumen.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: curl_multi_exec() has been disabled for security reasons (View: /home/mines/public_html/resourcecontracts/resources/views/layout/partials/head.blade.php) (View: /home/mines/public_html/resourcecontracts/resources/views/layout/partials/head.blade.php) in /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php:0
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#1 {main}
[2020-08-21 10:50:20] lumen.ERROR: ErrorException: curl_multi_exec() has been disabled for security reasons in /home/mines/public_html/resourcecontracts/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:238
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(2, 'curl_multi_exec...', '/home/mines/pub...', 238, Array)
#1 /home/mines/public_html/resourcecontracts/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(238): curl_multi_exec(Resource id #325, false)
#2 /home/mines/public_html/resourcecontracts/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles()
#3 /home/mines/public_html/resourcecontracts/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform()
#4 /home/mines/public_html/resourcecontracts/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send()
#5 /home/mines/public_html/resourcecontracts/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send()
#6 /home/mines/public_html/resourcecontracts/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php(256): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\Request))
#7 /home/mines/public_html/resourcecontracts/vendor/guzzle/guzzle/src/Guzzle/Service/Client.php(136): Aws\Common\Client\AbstractClient->send(Object(Guzzle\Http\Message\Request))
#8 /home/mines/public_html/resourcecontracts/vendor/guzzle/guzzle/src/Guzzle/Service/Command/AbstractCommand.php(153): Guzzle\Service\Client->execute(Object(Aws\S3\Command\S3Command))
#9 /home/mines/public_html/resourcecontracts/vendor/aws/aws-sdk-php/src/Aws/S3/S3Client.php(681): Guzzle\Service\Command\AbstractCommand->execute()
#10 /home/mines/public_html/resourcecontracts/vendor/aws/aws-sdk-php/src/Aws/S3/S3Client.php(429): Aws\S3\S3Client->checkExistenceWithCommand(Object(Aws\S3\Command\S3Command))
#11 /home/mines/public_html/resourcecontracts/vendor/league/flysystem-aws-s3-v2/src/AwsS3Adapter.php(125): Aws\S3\S3Client->doesObjectExist('resourcecontrac...', 'partners/EUb4K....')
#12 /home/mines/public_html/resourcecontracts/vendor/league/flysystem/src/Filesystem.php(57): League\Flysystem\AwsS3v2\AwsS3Adapter->has('partners/EUb4K....')
#13 /home/mines/public_html/resourcecontracts/vendor/illuminate/filesystem/FilesystemAdapter.php(42): League\Flysystem\Filesystem->has('partners/EUb4K....')
#14 /home/mines/public_html/resourcecontracts/app/Http/Services/Admin/PartnerService.php(71): Illuminate\Filesystem\FilesystemAdapter->exists('partners/EUb4K....')
#15 /home/mines/public_html/resourcecontracts/app/Http/Services/Admin/PartnerService.php(51): App\Http\Services\Admin\PartnerService->getImageUrl('partners/EUb4K....')
#16 /home/mines/public_html/resourcecontracts/app/Http/Controllers/SiteController.php(59): App\Http\Services\Admin\PartnerService->all()
#17 [internal function]: App\Http\Controllers\SiteController->home(Object(App\Http\Services\Admin\OptionService), Object(App\Http\Services\Admin\PartnerService))
#18 /home/mines/public_html/resourcecontracts/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#19 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1411): Illuminate\Container\Container->call(Array, Array)
#20 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1375): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#21 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1347): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\SiteController), 'home', Array)
#22 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1315): Laravel\Lumen\Application->callControllerAction(Array)
#23 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1300): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#24 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1215): Laravel\Lumen\Application->handleFoundRoute(Array)
#25 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(Illuminate\Http\Request))
#26 /home/mines/public_html/resourcecontracts/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 /home/mines/public_html/resourcecontracts/app/Http/Middleware/TrustedProxy.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: App\Http\Middleware\TrustedProxy->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/mines/public_html/resourcecontracts/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#30 /home/mines/public_html/resourcecontracts/app/Http/Middleware/Localization.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: App\Http\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/mines/public_html/resourcecontracts/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#33 /home/mines/public_html/resourcecontracts/vendor/illuminate/session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/mines/public_html/resourcecontracts/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/mines/public_html/resourcecontracts/vendor/illuminate/pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1451): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1221): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#40 /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php(1161): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#41 /home/mines/public_html/resourcecontracts/index.php(28): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#42 {main}
[2020-08-21 10:50:20] lumen.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: curl_multi_exec() has been disabled for security reasons (View: /home/mines/public_html/resourcecontracts/resources/views/layout/partials/head.blade.php) (View: /home/mines/public_html/resourcecontracts/resources/views/layout/partials/head.blade.php) in /home/mines/public_html/resourcecontracts/vendor/laravel/lumen-framework/src/Application.php:0
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#1 {main}
```

**Comment by iprunache** [comment]
All is good here, closing.
