### ISSUE TITLE
Country and Resource wise contract grouping

### ISSUE THREAD

**Issue by man-git007** [NRGI/resourcecontracts.org#1342]
## What
Need to group the contract by country-wise and resource-wise in subsite

## Notes
Same as free text search of a contract.

**Comment by surazneupane** [comment]
Grouping of contract resourse wise and country wise has been deployed in staging server please verify it . Thanks ! 
cc @man-git007  @anjesh  @SamCCSI @charlesyoung

**Comment by charlesyoung** [comment]
Looks good for RC, please move to Prod. 

@SamCCSI needs to approve the OLC update.

**Comment by SamCCSI** [comment]
Looks good. Only issue is that some have the drop-down arrow without having
any associated docs?

[image: image.png]

**Comment by charlesyoung** [comment]
Yep, an example from the Staging site (drop-down arrow without having any associated docs)

![image](https://user-images.githubusercontent.com/13888372/102125420-5a68f380-3e52-11eb-916f-c28879d6b952.png)

Same doc on the Prod site, with an associated doc. 

![image](https://user-images.githubusercontent.com/13888372/102125478-6fde1d80-3e52-11eb-9ffe-7f71ad446f6f.png)

Might also just be dirty data on the Staging site.

**Comment by surazneupane** [comment]
![countries](https://user-images.githubusercontent.com/37624741/102172435-d9951080-3ec0-11eb-93cb-6a4d850bd321.png)
@charlesyoung  @SamCCSI  The associated documents for above contracts are seen to be not published in Staging Server.

**Comment by charlesyoung** [comment]
Please deploy to the RC prod site.

**Comment by SamCCSI** [comment]
And OLC

(But I hope that any associated docs unpublished do not produce the arrow
on the live site)

Many thanks!

**Comment by surazneupane** [comment]
@charlesyoung  @SamCCSI  Can You see the changes in production? 
@SamCCSI  Can you see the arrow are not roduced in the production?

**Comment by charlesyoung** [comment]
Thanks, I don't see any issues as noted above. 

I do however have a question on the alignment of the first associated document as shown below. Can we keep the associated documents aligned? 

![image](https://user-images.githubusercontent.com/13888372/102218225-55558400-3ee6-11eb-83af-2a81c1609e43.png)

**Comment by surazneupane** [comment]
@charlesyoung  I think these two are not associated contract . I think these are main contract. Can you please check it Thanks !
![s1](https://user-images.githubusercontent.com/37624741/102221175-e8ec7c00-3f09-11eb-939a-4e0ca30ba86a.png)
![s2](https://user-images.githubusercontent.com/37624741/102221184-ebe76c80-3f09-11eb-86c6-ac2fe279f206.png)

**Comment by charlesyoung** [comment]
Nope, they are linked as shown below. 

![image](https://user-images.githubusercontent.com/13888372/102221564-f5151100-3eea-11eb-9cf5-6d6181119706.png)

**Comment by surazneupane** [comment]
@charlesyoung  soory i didn't get it. Did you mean we should align main and associated document?

**Comment by SamCCSI** [comment]
Working nicely, thanks!

>

**Comment by charlesyoung** [comment]
Scrape that. Thanks

**Comment by iprunache** [comment]
@charlesyoung @surazneupane  I see a lot of errors in the production logs after the changes to this issue.

For example, URLs like https://resourcecontracts.org/contracts/download/csv?lang=fr&country=mx&resource=&download=1 are not working and throwing the error.

Here's the full error log for troubleshooting.
```
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs [2020-12-18 08:58:30] lumen.ERROR: exception 'ErrorException' with message 'Undefined index: group' in /var/www/rc/app/Http/Services/APIService.php:103
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs Stack trace:
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #0 /var/www/rc/app/Http/Services/APIService.php(103): Laravel\Lumen\Application->Laravel\Lumen\{closure}(8, 'Undefined index...', '/var/www/rc/app...', 103, Array)
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #1 /var/www/rc/app/Http/Controllers/Contract/ContractController.php(250): App\Http\Services\APIService->allContracts(Array)
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #2 [internal function]: App\Http\Controllers\Contract\ContractController->downloadMetadataAsCSV(Object(Illuminate\Http\Request))
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #3 /var/www/rc/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #4 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1411): Illuminate\Container\Container->call(Array, Array)
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #5 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1376): Laravel\Lumen\Application->callControllerCallable(Array, Array)
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #6 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1347): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\Contract\ContractController), 'downloadMetadat...', Array)
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #7 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1315): Laravel\Lumen\Application->callControllerAction(Array)
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #8 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1300): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #9 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1215): Laravel\Lumen\Application->handleFoundRoute(Array)
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #10 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(Illuminate\Http\Request))
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #11 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #12 /var/www/rc/app/Http/Middleware/TrustedProxy.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #13 [internal function]: App\Http\Middleware\TrustedProxy->handle(Object(Illuminate\Http\Request), Object(Closure))
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #14 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #15 /var/www/rc/app/Http/Middleware/Localization.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #16 [internal function]: App\Http\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #17 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #18 /var/www/rc/vendor/illuminate/session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #19 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #20 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #21 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #22 /var/www/rc/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #23 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1451): Illuminate\Pipeline\Pipeline->then(Object(Closure))
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #24 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1221): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #25 /var/www/rc/vendor/laravel/lumen-framework/src/Application.php(1161): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #26 /var/www/rc/public/index.php(28): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-var-www-rc-storage-logs #27 {main}  
Dec 18 10:58:30 afcc85ed37aa ecs-rc-subsite-master-nginx-access.log ::ffff:10.0.0.53 - - [18/Dec/2020:08:58:30 +0000] "GET /contracts/download/csv?lang=fr&country=mx&resource=&download=1 HTTP/1.1" 200 6116 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
```

**Comment by charlesyoung** [comment]
Thanks @iprunache 

@surazneupane can you please look at what is causing this issue?

**Comment by surazneupane** [comment]
@charlesyoung @iprunache  please verify if the issue is solved in staging server.
@iprunache you may get changes in excel sheet in staging as we are working on other issues . Thanks!

**Comment by iprunache** [comment]
@surazneupane it still happens on staging but on a different route: https://staging.resourcecontracts.org/contracts .

I can't see other routes being affected on staging right now but, to make sure, please check all paths that can lead to the point of error.

**Comment by surazneupane** [comment]
@iprunache  updated and checked all routes going through error occured path  and solved the currrent issues . Please Check on staging server if any issues still exists thanks!

**Comment by iprunache** [comment]
@surazneupane Thanks, I haven't seen any errors on staging after you pushed the changes. I'll let you know if new errors show up in production after merging.

**Comment by surazneupane** [comment]
@iprunache can you verify if all good at production? And can this issue be closed ? Thanks!

**Comment by iprunache** [comment]
@surazneupane all errors stopped after your message, thanks! Feel free to close if all was implemented.
